[package]
name = #FIXME:
version = #FIXME:
edition = "2024" #FIXME:
description = #FIXME:
repository = #FIXME:
license-file = #FIXME:

[dependencies]
#FIXME:

[dev-dependencies]
#FIXME:

[lints.clippy]
pedantic = { level = "warn", priority = -100 }

[lints.rust]
unsafe_code = "forbid"
